/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pzx64
 */
public class MiJuego extends javax.swing.JFrame {

    Feid feid;
    Fantasma fantasma;

    /**
     * Creates new form MiJuego
     */
    public MiJuego() {
        initComponents();
        feid = new Feid(jPanel1);
        feid.Dir = "C:\\Users\\pzx64\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoJuego\\src\\imagenes\\feidD.png";
        Fantasma fantasma = new Fantasma(jPanel1);
        fantasma.Direccion = "C:\\Users\\pzx64\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoJuego\\src\\imagenes\\fantasma.png";
        fantasma.dibuja_fantasma(jPanel1.getGraphics(), 50, 50, fantasma.Direction());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        int x, y;
        x = feid.CordX();
        y = feid.CordY();
        String Direc = "";
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_SPACE:
                
                    Fantasma fantasma = new Fantasma(jPanel1);
                    fantasma.Direccion = "C:\\Users\\pzx64\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoJuego\\src\\imagenes\\fantasma.png";
                    fantasma.dibuja_fantasma(jPanel1.getGraphics(), 50, 50, fantasma.Direction());
                    break;
                
            case KeyEvent.VK_LEFT:
                if (feid.CordX() < -10) {
                    Direc = "C:\\Users\\pzx64\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoJuego\\src\\imagenes\\feidL.png";
                    feid.x = x;
                    feid.Dir = Direc;
                    break;
                } else {
                    x = x - 10;
                    Direc = "C:\\Users\\pzx64\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoJuego\\src\\imagenes\\feidL.png";
                    feid.x = x;
                    feid.Dir = Direc;
                    break;
                }

            case KeyEvent.VK_RIGHT:
                if (feid.CordX() > 550) {
                    Direc = "C:\\Users\\pzx64\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoJuego\\src\\imagenes\\feidD.png";
                    feid.x = x;
                    feid.Dir = Direc;
                    break;
                } else {
                    x = x + 10;
                    Direc = "C:\\Users\\pzx64\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoJuego\\src\\imagenes\\feidD.png";
                    feid.x = x;
                    feid.Dir = Direc;
                    break;
                }

            case KeyEvent.VK_UP:
                y = y - 50;
                Direc = "C:\\Users\\pzx64\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoJuego\\src\\imagenes\\feidA.png";
                feid.y = y;
                feid.Dir = Direc;
                feid.Dibuja_feid(jPanel1.getGraphics(), x, y, Direc);
                y = y + 50;
                Direc = "C:\\Users\\pzx64\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoJuego\\src\\imagenes\\feidA.png";
                feid.y = y;
                feid.Dir = Direc;
                break;
            case KeyEvent.VK_DOWN:
                Direc = "C:\\Users\\pzx64\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoJuego\\src\\imagenes\\feidD.png";
                feid.y = y;
                feid.Dir = Direc;
                feid.Dibuja_feid(jPanel1.getGraphics(), x, y, Direc);
                break;
        }
        feid.Dibuja_feid(jPanel1.getGraphics(), x, y, Direc);
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MiJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
